### ISSUE TITLE
Recommendations for analyisis (Microarray as training with RNAseq to classify)

### ISSUE THREAD

**Issue by ahwanpandey** [CityUHK-CompBio/DeepCC#11]
Hello,

Thanks for the tool deepCC. I have a few questions about recommended workflows:

**1. I have a High Grade Serous Ovarian Cancer microarray dataset with about 230 samples classified into 4 molecular subtypes to be used as a training dataset.**
- Can I use this microarray dataset as training dataset for RNAseq samples?
- Do you recommend doing any filtering on this dataset before `getFunctionalSpectra `and `train_DeepCC_model`?
- All I am doing is keeping the probe per gene with the highest mean expression across all samples. Is this good enough? Should I filter further for most variable genes or with at least "X" expression across the samples?

**2. I have 131 RNAseq samples run on various different library preps (some stranded, some unstranded) which I need to classify.**
- Is it OK to use the above microarray dataset to classify these RNAseq samples?
- Do you recommend any filtering/preprocessing on this RNAseq matrix? 
- There will be some genes that are only expressed in the stranded dataset because of the assay, should I remove these? Note: if I batch corrected this data, it mostly takes care of this issue.
- Do you recommend log2(TPM+1) data or log2(TMM) data?
- Do I need to batch correct before classifying?
- At the moment, I am using batch corrected log2(TMM) values which is giving results that make sense; but if I used log2(TPM+1) with no batch correction, the results are very different.

Thanks for your input!
Ahwan

**Comment by zero19970** [comment]
Hi, 

Thanks for using our DeepCC tools. Following are some replys for your questions:

1. You can use the High Grade Serous Ovarian Cancer microarray dataset as training dataset.  
2. You can apply ```log2(TPM+1e-6)``` to the gene expression profiles (eps) before ```getFunctionalSpectra``` without any other filtering procession. After ```getFunctionalSpectra```, the eps was transformed from original dimension to the sets number of  MSigDBv7  (22, 596 gene sets) for each patient sample.
3. I think it's fine to classify the 131 RNAseq as long as them are the same cancer types with the training dataset.
4. Our ```getFunctionalSpectra``` can deal with dataset with batch effect. So you neet not to do additional batch correct.
5. LogChange with ```log2(TPM + 1)``` and ```log2(TMM)``` should make no much difference. Just keep training dataset and test dataset with the sample logChange. The varied results maybe caused by lack of enough training samples. Also, the classification results are related to how good the molecular subtype of the training dataset.

Best wish!
LeeCH

**Comment by ahwanpandey** [comment]
Thank you for your response!
