### ISSUE TITLE
Single sample on DeepCC online problems

### ISSUE THREAD

**Issue by Armuchang** [CityUHK-CompBio/DeepCC#13]
Hi, I'm writing this for informing you about my problem with DeepCC online predicting a single sample of gene expression data. I've tried to use SYMBOL and ALIAS gene annotation instead of ENTREZ ID for my single sample but it doesn't work for frequency spectrum calculation. However, it works when using ENTREZ ID. I'm not sure that it depends on your design or it's a bug of this platform. Please, let me know if you have some updates or anything about this issue.

Thanks,
Armu

**Comment by zero19970** [comment]
Hi Armu,
You can only use ENTREZ ID for a single sample of gene expression. This is because when calculating for a single sample, there need to be a reference to judge whether the expression of each gene up-regulation or down-regulation, and this is calculated according to the average expression of each gene in TCGA gene expression matrix which uses ENTREZ ID for index.
You can use BioConductor package "org.Hs.eg.db" to convert SYMBOL to ENTREZ ID.
Best regards!
Chenghang LI
