### ISSUE TITLE
Error in mx.opt.sgd(...)

### ISSUE THREAD

**Issue by GF851** [CityUHK-CompBio/DeepCC#3]
Dears,
I am trying to run a DeepCC model using trainDeepCCModel, but I got an error message.
deepcc.model <- trainDeepCCModel(fs, labels)
Error in mx.opt.sgd(...) : unused argument (device = device)

I am relatively new to DeepCC so any help is greatly appreciated!
All the best!

**Comment by gaofeng21cn** [comment]
Hi,

I checked the error message and I think it is caused by mxnet. They changed the parameter name inside their function from 'device' to 'ctx'. 

Since we are in the middle of changing the deep learning backend from mxnet to keras, which has official support from RStudio, we don't have test environment to re-test the new change made by mxnet. But I made a temporary patch for it. If that is the only problem here, you can fix it by installing the latest version of DeepCC from GitHub.
